#!/usr/bin/env node

// ESM modules
require = require('esm')(module);

// Dependencies
const os = require('os');
const fs = require('fs');
const { execSync } = require('child_process');
const waitOn = require('wait-on');
// const execa = require('execa');
const { TestManager } = require('./utils/TestManager');
const yargv = require('yargs').argv;

const waitOnPromise = options => new Promise(resolve => waitOn(options, resolve));

(async () => {
  const tm = new TestManager('packages/tests');
  const [command, name, arg0] = yargv._;

  if (!fs.existsSync('packages/tests/base/src/main.js')) {
    await tm.initBase();
  }

  if (!fs.existsSync(`packages/tests/${name}/src/main.js`)) {
    await tm.create(name);
  }

  switch (command) {
    /**
     * Install fixtures on project
     */
    case 'install:fixtures':
    case 'if':
      await tm.installFixtures(name, `tests/${name}/fixtures`);
      break;

    /**
     * Invoke a Vue CLI plugin on project
     */
    case 'install:invoke':
    case 'ii':
      await tm.invoke(name, arg0);
      break;

    /**
     * Create a full test project
     */
    case 'install':
    case 'i':
      await tm.installFixtures(name, `tests/${name}/fixtures`);
      await tm.invoke(name, arg0);
      break;

    /**
     * Run tests
     */
    case 'test':
    case 't':
      await tm.cliService(name, 'ssr:build');

      const server = tm.cliService(name, 'ssr:start');

      await waitOnPromise({
        resources: [`tcp:localhost:8080`],
        timeout: 60 * 1000,
      });

      const jest = require('execa')(
        './node_modules/.bin/jest',
        ['--config', `tests/${name}/jest.config.js`],
        {
          stdio: 'inherit',
        },
      );

      jest.on('exit', exitCode => {
        if (server) {
          if (os.platform() === 'win32') {
            execSync(`taskkill /F /T /PID ${server.pid}`);
          } else {
            server.kill('SIGINT');
          }
        }

        console.log(`Exit code: ${exitCode}`);
        process.exit(exitCode);
      });
      break;
  }
})().catch(err => console.error(err));
